### ISSUE TITLE
Missing `alt` attribute 

### ISSUE THREAD

**Issue by wehelie** [wehelie/article_mockup#2]
@karim33, 

Your image is missing an `alt` attribute. The required `alt` attribute specifies an alternate text for an image, if the image cannot be displayed. The `alt` attribute provides alternative information for an image if a user for some reason cannot view it (because of slow connection, an error in the `src` attribute, or if the user uses a screen reader).

- - - 
Example:
- - - 

```HTML
 <img src="cat.gif" alt="running cat">
```

**Comment by karim33** [comment]
any particular alt name for this gif?

**Comment by wehelie** [comment]
You could call it anything you want, but it should reflect the actual image.

**Comment by karim33** [comment]
@wehelie, I made the changes

**Comment by wehelie** [comment]
@karim33 fixed.
